name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Prepare dummy model artifacts (so API can import)
        run: |
          python - <<'PY'
          import os, json, joblib, numpy as np, pandas as pd
          from sklearn.compose import ColumnTransformer
          from sklearn.pipeline import Pipeline
          from sklearn.preprocessing import OneHotEncoder
          from sklearn.linear_model import LinearRegression

          os.makedirs("models", exist_ok=True)
          features = ["room_type","neighbourhood","accommodates","bedrooms","bathrooms_num",
                      "minimum_nights","number_of_reviews","reviews_per_month","availability_365"]

          n = 20
          df = pd.DataFrame({
              "room_type": np.random.choice(["Entire home/apt","Private room"], n),
              "neighbourhood": np.random.choice(["Mitte","Kreuzberg","Wedding"], n),
              "accommodates": np.random.randint(1,5,n),
              "bedrooms": np.random.randint(1,3,n).astype(float),
              "bathrooms_num": np.random.choice([1.0,1.5], n),
              "minimum_nights": np.random.randint(1,5,n),
              "number_of_reviews": np.random.randint(0,50,n),
              "reviews_per_month": np.random.rand(n),
              "availability_365": np.random.randint(0,365,n),
          })
          y = 50 + 10*df["bedrooms"].values + 5*df["accommodates"].values + np.random.randn(n)*2

          categorical = ["room_type","neighbourhood"]
          pre = ColumnTransformer([("cat", OneHotEncoder(handle_unknown="ignore"), categorical)],
                                  remainder="passthrough")
          model = Pipeline([("prep", pre), ("reg", LinearRegression())]).fit(df[features], y)

          joblib.dump(model, "models/baseline.joblib")
          with open("models/baseline.joblib.meta.json","w",encoding="utf-8") as f:
              json.dump({"features": features, "metrics": None, "created": None}, f)
          PY

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q

  build-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t airbnb-api .
